function kickbox_test(){var O='',sb='" for "gwt:onLoadErrorFn"',qb='" for "gwt:onPropertyErrorFn"',_='"><\/script>',bb='#',Ab='&',Tb='.cache.html',db='/',Sb=':',kb='::',_b='<script defer="defer">kickbox_test.onInjectionDone(\'kickbox_test\')<\/script>',$='<script id="',nb='=',cb='?',pb='Bad handler "',$b='DOMContentLoaded',Rb="GWT module 'kickbox_test' may need to be (re)compiled",ab='SCRIPT',Db='Unexpected exception in locale detection, using default: ',Cb='_',Bb='__gwt_Locale',Y='__gwt_marker_kickbox_test',eb='base',Z='baseUrl',S='begin',R='bootstrap',gb='clear.cache.gif',mb='content',yb='default',X='end',Lb='gecko',Mb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',Ub='gwt/standard/standard.css',rb='gwt:onLoadErrorFn',ob='gwt:onPropertyErrorFn',lb='gwt:property',Zb='head',Pb='hosted.html?kickbox_test',Yb='href',Kb='ie6',Jb='ie8',tb='iframe',fb='img',ub="javascript:''",P='kickbox_test',jb='kickbox_test::',Vb='link',Ob='loadExternalRefs',xb='locale',zb='locale=',hb='meta',wb='moduleRequested',W='moduleStartup',Ib='msie',ib='name',Fb='opera',vb='position:absolute;width:0;height:0;border:none',Wb='rel',Hb='safari',Qb='selectingPermutation',Q='startup',Xb='stylesheet',Nb='unknown',Eb='user.agent',Gb='webkit';var k=window,l=document,m=k.__gwtStatsEvent?function(a){return k.__gwtStatsEvent(a)}:null,n=k.__gwtStatsSessionId?k.__gwtStatsSessionId:null,o,p,q,r=O,s={},t=[],u=[],v=[],w=0,x,y;m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!k.__gwt_stylesLoaded){k.__gwt_stylesLoaded={}}if(!k.__gwt_scriptsLoaded){k.__gwt_scriptsLoaded={}}function z(){var b=false;try{var c=k.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||k.external&&k.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}z=function(){return b};return b}
function A(){if(o&&p){var b=l.getElementById(P);var c=b.contentWindow;if(z()){c.__gwt_getProperty=function(a){return G(a)}}kickbox_test=null;c.gwtOnLoad(x,P,r,w);m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function B(){var e,f=Y,g;if(s[Z]){r=s[Z];return}l.write($+f+_);g=l.getElementById(f);e=g&&g.previousSibling;while(e&&e.tagName!=ab){e=e.previousSibling}function h(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
;if(e&&e.src){r=h(e.src)}if(r==O){var i=l.getElementsByTagName(eb);if(i.length>0){r=i[i.length-1].href}else{r=h(l.location.href)}}else if(r.match(/^\w+:\/\//)){}else{var j=l.createElement(fb);j.src=r+gb;r=h(j.src)}if(g){g.parentNode.removeChild(g)}}
function C(){var b=document.getElementsByTagName(hb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(ib),g;if(f){f=f.replace(jb,O);if(f.indexOf(kb)>=0){continue}if(f==lb){g=e.getAttribute(mb);if(g){var h,i=g.indexOf(nb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}s[f]=h}}else if(f==ob){g=e.getAttribute(mb);if(g){try{y=eval(g)}catch(a){alert(pb+g+qb)}}}else if(f==rb){g=e.getAttribute(mb);if(g){try{x=eval(g)}catch(a){alert(pb+g+sb)}}}}}}
function D(a,b){return b in t[a]}
function E(a){var b=s[a];return b==null?null:b}
function G(a){var b=u[a](),c=t[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(y){y(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=l.createElement(tb);a.src=ub;a.id=P;a.style.cssText=vb;a.tabIndex=-1;l.body.appendChild(a);m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:wb});a.contentWindow.location.replace(r+K)}}
u[xb]=function(){try{var b;var c=yb||yb;if(b==null){var d=location.search;var e=d.indexOf(zb);if(e>=0){var f=d.substring(e);var g=f.indexOf(nb)+1;var h=f.indexOf(Ab);if(h==-1){h=f.length}b=f.substring(g,h)}}if(b==null){b=E(xb)}if(b==null){b=k[Bb]}else{k[Bb]=b||c}if(b==null){return c}while(!D(xb,b)){var i=b.lastIndexOf(Cb);if(i==-1){b=c;break}else{b=b.substring(0,i)}}return b}catch(a){alert(Db+a);return yb}};t[xb]={de:0,'default':1,en:2};u[Eb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Fb)!=-1){return Fb}else if(b.indexOf(Gb)!=-1){return Hb}else if(b.indexOf(Ib)!=-1){if(document.documentMode>=8){return Jb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Kb}}}}else if(b.indexOf(Lb)!=-1){var d=/rv:([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){if(c(d)>=1008)return Mb}return Lb}return Nb};t[Eb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};kickbox_test.onScriptLoad=function(){if(H){p=true;A()}};kickbox_test.onInjectionDone=function(){o=true;m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:Ob,millis:(new Date).getTime(),type:X});A()};C();B();var J;var K;if(z()){if(k.external&&(k.external.initModule&&k.external.initModule(P))){k.location.reload();return}K=Pb;J=O}m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Qb});if(!z()){try{alert(Rb);return;var L=J.indexOf(Sb);if(L!=-1){w=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Tb}catch(a){return}}var M;function N(){if(!q){q=true;if(!__gwt_stylesLoaded[Ub]){var a=l.createElement(Vb);__gwt_stylesLoaded[Ub]=a;a.setAttribute(Wb,Xb);a.setAttribute(Yb,r+Ub);l.getElementsByTagName(Zb)[0].appendChild(a)}A();if(l.removeEventListener){l.removeEventListener($b,N,false)}if(M){clearInterval(M)}}}
if(l.addEventListener){l.addEventListener($b,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(l.readyState)){I();N()}},50);m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});m&&m({moduleName:P,sessionId:n,subSystem:Q,evtGroup:Ob,millis:(new Date).getTime(),type:S});l.write(_b)}
kickbox_test();